#!/usr/bin/env bash
# GiraHelper v1
# Copyright (C) 2013 Jonas Friedmann

# Get passed arguments
args="${@}"

# Check for args
if [[ ${args} != "ein" &&  ${args} != "aus" ]]; then
  echo "Invalid argument: has to be 'ein' or 'aus'."
  exit
fi

# load config file
. ${HOME}/.gira.cfg

# Function to send Notification Center messages
function notification {
   /Applications/terminal-notifier.app/Contents/MacOS/terminal-notifier -title "Gira" -message "${@}"
}

# For each outlet defined in config
for i in "${OUTLETS[@]}"; do
  printf "Calling outlet 'licht0${i}${args}'... "
  curl -s "${SERVER}/${OFFICE}licht0${i}${args}"
  notification "Verbinde zu Outlet '${OFFICE}/0${i}${args}' ..." >/dev/null 2>&1
  printf "done\n"
done
