#!/usr/bin/env bash
# GiraHelper v1
# Copyright (C) 2013 Jonas Friedmann

# Variables
notifierBin="/Applications/terminal-notifier.app/Contents/MacOS/terminal-notifier"
notifierBool=false

# Get passed arguments
args="${*}"

# Check for args
if [[ ${args} != "on" &&  ${args} != "off" &&  ${args} != "config" ]]; then
  echo "Invalid argument: has to be 'on', 'off' or 'config'."
  exit 1
fi

# Check for config file
if [[ ! -f ~/.gira.conf ]]; then
  echo "Missing configuration file: ~/.gira.conf"
  exit 1
fi

# Check for terminal-notifier
if [[ -f "${notifierBin}" ]]; then
  notifierBool=true
fi

# Load config file
. ~/.gira.conf

# Function to send Notification Center messages
function notification {
    # Speed up execution by executing next command in the background
    notifierBool && /Applications/terminal-notifier.app/Contents/MacOS/terminal-notifier -title "Gira" -message "${@}" &
}

# Translate state
if [[ "$args" == "on" ]]; then
  state="ein"
elif [[ "$args" == "off" ]]; then
  state="aus"
elif [[ "$args" == "config" ]]; then
  for i in "${OUTLETS[@]}"; do
    echo "${OFFICE}:0${i}"
  done
  exit 0
fi

# For each outlet defined in config
for i in "${OUTLETS[@]}"; do
  printf "Trigger outlet '%s:0%s (%s)'... " "${OFFICE}" "${i}" "${args}"
  curl -s "${SERVER}/${OFFICE}licht0${i}${state}"
  notification "Trigger outlet '${OFFICE}:0${i} (${args})' ..." >/dev/null 2>&1
  printf "done\n"
done

exit 0
