#!/usr/bin/env bash
# GiraHelper v1
# Copyright (C) 2013 Jonas Friedmann

# Get passed arguments
args="${*}"

# Check for args
if [[ ${args} != "on" &&  ${args} != "off" ]]; then
  echo "Invalid argument: has to be 'on' or 'off'."
  exit 1
fi

# Check for config file
if [[ ! -f ~/.gira.conf ]]; then
  echo "Missing configuration file: ~/.gira.conf"
  exit 1
fi

# Check for terminal-notifier
if [[ ! -f /Applications/terminal-notifier.app/Contents/MacOS/terminal-notifier ]]; then
  echo "Missing dependency: terminal-notifier"
  exit 1
fi

# load config file
. ~/.gira.conf

# Function to send Notification Center messages
function notification {
   /Applications/terminal-notifier.app/Contents/MacOS/terminal-notifier -title "Gira" -message "${@}"
}

# Translate state
if [[ "$args" == "on" ]]; then
  state="ein"
elif [[ "$args" == "off" ]]; then
  state="aus"
fi

# For each outlet defined in config
for i in "${OUTLETS[@]}"; do
  printf "Trigger outlet '%s:0%s (%s)'... " "${OFFICE}" "${i}" "${args}"
  curl -s "${SERVER}/${OFFICE}licht0${i}${state}"
  notification "Trigger outlet '${OFFICE}:0${i} (${args})' ..." >/dev/null 2>&1
  printf "done\n"
done
